<?php
/** @var $this Hips_Hipspay_Block_Form */

$_form = $this;
$_code = $_form->getMethodCode();
$_method = $_form->getMethod();

?>


<!-- normal form-->
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <input type="hidden" value="" id="<?php echo $_code ?>_card_token" name="payment[card_token]"/>

    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number validate-cc-type" value="" data-hips-tokenizer="number" maxlength="16"/>
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" class="month validate-cc-exp required-entry" data-hips-tokenizer="exp_month">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" class="year required-entry" data-hips-tokenizer="exp_year">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>

    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" value="" data-hips-tokenizer="cvc" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>

</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
<script type="text/javascript">
    //<![CDATA[

    var HPPayment = Class.create(Payment, {
        save: function($super, validated) {
            // Ignore this overridden method if the current method isn't HipsPay
            if(this.currentMethod != "<?php echo $_code ?>") {
                $super();
                return;
            }
            else {
                tokenize($super);
            }
        }
    });

    // override the default payment class
    payment = new HPPayment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    //]]>
</script>
